config/routes.rb
Rails.application.routes.draw do
  root to: "tournaments#index"

  resources :teams
  resources :tournaments do
    resources :tournament_entrants
    resources :matches do
      collection do
        get 'generate_results_for_all_matches'
      end
    end
    member do
      get 'generate_matches'
      get 'generate_playoff_matches'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
  enum group: %i[group_a group_b playoff]

  belongs_to :tournament
  belongs_to :winner, class_name: 'Team', optional: true
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :tournament_entrants
  has_many :tournaments, through: :tournament_entrants

  validates :name, presence: true, uniqueness: true
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  enum status: { draft: 0, in_progress: 1, done: 2 }

  has_many :matches
  has_many :tournament_entrants
  has_many :teams, through: :tournament_entrants

  validates :name, presence: true, uniqueness: true
end

app/models/tournament_entrant.rb
class TournamentEntrant < ApplicationRecord
  enum competition_type: %i[group_a group_b playoff]

  belongs_to :team
  belongs_to :tournament
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[show edit update destroy]
  before_action :set_tournament, only: %i[index show new create edit update generate_results_for_all_matches]

  def index
    @matches = @tournament.matches
  end

  def edit
  end

  def show
  end

  def new
    @match = Match.new
  end

  def create
    @match = Match.new(match_params)

    if @match.save
      redirect_to @match, notice: "Match was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @match.update(match_params)
      redirect_to tournament_match_url(@tournament, @match), notice: "Match was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def generate_results_for_all_matches
    @tournament.matches.each { |match| GroupMatchPlayService.new(match).call }
    redirect_to tournament_matches_path(@tournament)
  end

  private

  def set_match
    @match = Match.find(params[:id])
  end

  def set_tournament
    @tournament = Tournament.find(params[:tournament_id])
  end

  def match_params
    params.require(:match).permit(:tournament_id, :first_team, :second_team, :winner_id, :group)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[ show edit update destroy ]

  def index
    @teams = Team.all
  end

  def show
  end

  def new
    @team = Team.new
  end

  def edit
  end

  def create
    @team = Team.new(team_params)

    if @team.save
      redirect_to @team, notice: "Team was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @team.update(team_params)
      redirect_to @team, notice: "Team was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @team.destroy
    redirect_to teams_url, notice: "Team was successfully destroyed."
  end

  private
    def set_team
      @team = Team.find(params[:id])
    end

    def team_params
      params.require(:team).permit(:name)
    end
end

app/controllers/tournament_entrants_controller.rb
class TournamentEntrantsController < ApplicationController
  before_action :set_tournament
  before_action :set_tournament_entrant, only: [:show, :edit, :update, :destroy]

  def index
    @tournament_entrants = @tournament.tournament_entrants
  end

  def show
  end

  def new
    @tournament_entrant = TournamentEntrant.new
  end

  def edit
  end

  def create
    @tournament_entrant = TournamentEntrant.new(tournament_entrant_params)

    if @tournament_entrant.save
      redirect_to @tournament, notice: "Tournament Entrant was successfully created."
    else
      render @tournament, status: :unprocessable_entity
    end
  end

  def update
    if @tournament_entrant.update(tournament_entrant_params)
      redirect_to @tournament_entrant, notice: "Tournament Entrant was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tournament_entrant.destroy
    redirect_to tournament_tournament_entrants_path, notice: "Tournament Entrant was successfully destroyed."
  end

  private

  def set_tournament
    @tournament ||= Tournament.find(params[:tournament_id])
  end

  def set_tournament_entrant
    @tournament_entrant = TournamentEntrant.find(params[:id])
  end

  def tournament_entrant_params
    params.require(:tournament_entrant).permit(:team_id, :tournament_id, :team_eliminated, :competition_type)
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: %i[ show edit update destroy generate_matches generate_playoff_matches]

  def index
    @tournaments = Tournament.all
  end

  def show
    @winners = @tournament.matches.where(winner_id: nil).exists?
  end

  def new
    @tournament = Tournament.new
  end

  def edit
  end

  def create
    @tournament = Tournament.new(tournament_params)

    result = Tournaments::SaveTournament.new(@tournament, params).perform if params.dig(:tournament, :team_ids).present?

    if (result.present? && result.success?) || @tournament.save
      redirect_to @tournament, notice: "Tournament was successfully created."
    else
      render :new
    end
  end

  def update
    if @tournament.update(tournament_params)
      redirect_to @tournament, notice: "Tournament was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tournament.destroy
    redirect_to tournaments_url, notice: "Tournament was successfully destroyed."
  end

  def generate_matches
    MatchesGeneratorService.new(@tournament).call
    redirect_to tournament_matches_path(@tournament)
  end

  def generate_playoff_matches
    PlayoffMatchesGeneratorService.new(@tournament).call
    redirect_to tournaments_url
  end

  private
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    def tournament_params
      params.require(:tournament).permit(:name, :status, :finalist)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tournament_entrants_helper.rb
module TournamentEntrantsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/divisions/_form.html.erb
<%= form_with(model: division) do |form| %>
  <% if division.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(division.errors.count, "error") %> prohibited this division from being saved:</h2>

      <ul>
        <% division.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/divisions/edit.html.erb
<h1>Editing Division</h1>

<%= render 'form', division: @division %>

<%= link_to 'Show', @division %> |
<%= link_to 'Back', divisions_path %>

app/views/divisions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Divisions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @divisions.each do |division| %>
      <tr>
        <td><%= link_to 'Show', division %></td>
        <td><%= link_to 'Edit', edit_division_path(division) %></td>
        <td><%= link_to 'Destroy', division, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Division', new_division_path %>

app/views/divisions/new.html.erb
<h1>New Division</h1>

<%= render 'form', division: @division %>

<%= link_to 'Back', divisions_path %>

app/views/divisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @division.name %>
</p>

<h3> Tournament Brackets</h3>

<% @division.teams.each_slice(2).to_a.each do |team| %>
  <ul>
    <li><%= team[0].name %> - <%= team[1].name %></li>
  </ul>
<% end %>

<%= link_to 'Start Matches', new_tournament_division_match_path(@tournament, @division) %>
<%= link_to 'Generate results for match', generate_match_result_tournament_division_path(@tournament, @division) %>
<%= link_to 'Edit', edit_division_path(@division) %> |
<%= link_to 'Back', divisions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTournamentScoring</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/matches/_form.html.erb
<%= form_with(model: [tournament, match]) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :winner %>
    <%= form.select :winner_id,
                    options_for_select([[Team.find(@match.first_team).name, Team.find(@match.first_team).id],
                                        [Team.find(@match.second_team).name, Team.find(@match.second_team).id]]),
                    include_blank: false %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', tournament: @tournament, match: @match %>

<%= link_to 'Show', tournament_match_url(@tournament, @match) %> |
<%= link_to 'Back', tournament_matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Matches</h1>

<% %i[group_a group_b].each do |group| %>
  <table>
    <thead>
    <tr>
      <th>First Player Id</th>
      <th>Second Player Id</th>
      <th>Group</th>
      <th>Winner</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <h3> <%= "#{group.to_s.titleize}" %> </h3>
    <% @matches.where(group: group).each do |match| %>
      <tr>
        <td><%= Team.find(match.first_team).name %></td>
        <td><%= Team.find(match.second_team).name %></td>
        <td><%= match.group %></td>
        <td><%= match.winner.present? ? match.winner.name : 'Game pending' %></td>
        <td><%= link_to 'Show', tournament_match_path(@tournament, match) %></td>
        <td><%= link_to 'Select winner', edit_tournament_match_path(@tournament, match) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>First Player Id</th>-->
<!--      <th>Second Player Id</th>-->
<!--      <th>Group</th>-->
<!--      <th>Winner</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--  <h3> First Division </h3>-->
  <%# @matches.where(group: :group_a).each do |match| %>
<!--    <tr>-->
<!--      <td><%#= Team.find(match.first_team).name %></td>-->
<!--      <td><%#= Team.find(match.second_team).name %></td>-->
<!--      <td><%#= match.group %></td>-->
<!--      <td><%#= match.winner.present? ? match.winner.name : 'Game pending' %></td>-->
<!--      <td><%#= link_to 'Show', tournament_match_path(@tournament, match) %></td>-->
<!--      <td><%#= link_to 'Select winner', edit_tournament_match_path(@tournament, match) %></td>-->
<!--    </tr>-->
  <%# end %>
<!--  </tbody>-->
<!--</table>-->

<!--<table>-->
<!--  <thead>-->
<!--  <tr>-->
<!--    <th>First Player Id</th>-->
<!--    <th>Second Player Id</th>-->
<!--    <th>Group</th>-->
<!--    <th>Winner</th>-->
<!--    <th colspan="3"></th>-->
<!--  </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--  <h3> Second Division </h3>-->
  <%# @matches.where(group: :group_b).each do |match| %>
<!--    <tr>-->
<!--      <td><%#= Team.find(match.first_team).name %></td>-->
<!--      <td><%#= Team.find(match.second_team).name %></td>-->
<!--      <td><%#= match.group %></td>-->
<!--      <td><%#= match.winner.present? ? match.winner.name : 'Game pending' %></td>-->
<!--      <td><%#= link_to 'Show', tournament_match_path(@tournament, match) %></td>-->
<!--      <td><%#= link_to 'Select winner', edit_tournament_match_path(@tournament, match) %></td>-->
<!--    </tr>-->
  <%# end %>
<!--  </tbody>-->
<!--</table>-->

<%= link_to 'Generate results for all matches', generate_results_for_all_matches_tournament_matches_path(@tournament)  %>
<%= link_to 'Back to tournament', tournament_url(@tournament) %>
<%= link_to 'Back to tournaments list', tournaments_url %>

<br>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match, tournament: @tournament, division: @division %>

<%= link_to 'Back', tournament_division_matches_path(@tournament, @division) %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Team:</strong>
  <%= Team.find(@match.first_team).name %>
</p>

<p>
  <strong>Second Team:</strong>
  <%= Team.find(@match.second_team).name %>
</p>

<p>
  <strong>Group:</strong>
  <%= @match.group %>
</p>

<p>
  <strong>Winner:</strong>
  <%= @match.winner.name if @match.winner.present? %>
</p>

<%= link_to 'Edit', edit_tournament_match_path(@tournament, @match) %>
<%= link_to 'Back', tournament_matches_path(@tournament) %>

app/views/tournament_entrants/_form.html.erb
<%= form_with(model: [@tournament, tournament_entrant]) do |form| %>
  <% if tournament_entrant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tournament_entrant.errors.count, "error") %> prohibited this tournament_entrant from being saved:</h2>

      <ul>
        <% tournament_entrant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :team %>
    <%= form.select :team_id, Team.where.not(id: Team.where(id: TournamentEntrant.all.pluck(:team_id)).pluck(:id)).collect { |p| [p.name, p.id] } %>
  </div>

  <%= form.hidden_field :tournament_id, value: @tournament.id %>

  <div class="field">
    <% %i[group_a group_b].each do |group| %>
      <% unless @tournament.tournament_entrants.where(competition_type: group).count == 8 %>
        <%= form.label :competition_type %>
        <%= form.select :competition_type, TournamentEntrant.competition_types.keys.first(2).reject { |key| key if @tournament.tournament_entrants.where(competition_type: key).count == 8 } %>
      <% end %>
  <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tournament_entrants/edit.html.erb
<h1>Editing Tournament Entrant</h1>

<%= render 'form', tournament_entrant: @tournament_entrant %>

<%= link_to 'Show', @tournament_entrant %> |
<%= link_to 'Back', tournament_entrants_path %>

app/views/tournament_entrants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tournament Entrants</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tournament_entrants.each do |tournament_entrant| %>
      <tr>
        <td><%= link_to 'Show', tournament_entrant %></td>
        <td><%= link_to 'Edit', edit_tournament_entrant_path(tournament_entrant) %></td>
        <td><%= link_to 'Destroy', tournament_entrant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tournament Entrant', new_tournament_entrant_path %>

app/views/tournament_entrants/new.html.erb
<h1>New Tournament Entrant</h1>

<%= render 'form', tournament_entrant: @tournament_entrant %>

<%= link_to 'Back', tournament_entrants_path %>

app/views/tournament_entrants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @tournament_entrant.team.name %>
</p>

<p>
  <strong>Tournament:</strong>
  <%= @tournament_entrant.tournament.name %>
</p>

<p>
  <strong>Competition Type:</strong>
  <%= @tournament_entrant.tournament.competition_type %>
</p>


<%= link_to 'Edit', edit_tournament_entrant_path(@tournament_entrant) %> |
<%= link_to 'Back', tournament_entrants_path %>

app/views/tournaments/_form.html.erb
<%= form_with(model: tournament) do |form| %>
  <% if tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
        <% tournament.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= collection_check_boxes(:tournament, :team_ids, Team.all, :id, :name, { include_hidden: false }) %>
  </div>

  <%= link_to 'Create Team', new_team_path  %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing Tournament</h1>

<%= render 'form', tournament: @tournament %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tournaments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Finalist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= tournament.name %></td>
        <td><%= tournament.status %></td>
        <td><%= Team.find(tournament.finalist).name if tournament.finalist.present? %></td>
        <td><%= link_to 'Show', tournament %></td>
        <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
        <td><%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tournament', new_tournament_path %>

app/views/tournaments/new.html.erb
<h1>New Tournament</h1>

<%= render 'form', tournament: @tournament %>

<%= link_to 'Back', tournaments_path %>

app/views/tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tournament.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @tournament.status %>
</p>

<h3> First Division </h3>
<% @tournament.teams.joins(:tournament_entrants).where(tournament_entrants: { competition_type: :group_a }).distinct.each do |team| %>
  <ul>
    <li><%= team.name %></li>
  </ul>
<% end %>

<h3> Second Division </h3>
<% @tournament.teams.joins(:tournament_entrants).where(tournament_entrants: {competition_type: :group_b }).distinct.each do |team| %>
  <ul>
    <li><%= team.name %></li>
  </ul>
<% end %>

<%= render 'tournament_entrants/form', tournament_entrant: @tournament.tournament_entrants.new %>

<%= link_to 'Edit', edit_tournament_path(@tournament) %> |
<%= link_to 'Back', tournaments_path %>

<% if @tournament.matches.present? %>
  <%= link_to 'Show Matches', tournament_matches_path(@tournament) %>
<% else %>
  <%= link_to 'Generate Matches', generate_matches_tournament_path(@tournament) %>
<% end %>

<% unless @winners %>
  <%= link_to 'Generate Playoff Brackets', generate_playoff_matches_tournament_url(@tournament) %>
<% end %>